class ErrorCode:
    UNKNOWN_ERROR = 'UNKNOWN_ERROR'
    API_ERROR = 'API_ERROR'
    VALIDATION_ERROR = 'VALIDATION_ERROR'
    AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'
    PERMISSION_ERROR = 'PERMISSION_ERROR'
    NOT_FOUND = 'NOT_FOUND' 