# Generated by Django 4.2.9 on 2025-01-15 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("search", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="searchlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="searchlog",
            index=models.Index(fields=["query"], name="search_sear_query_465835_idx"),
        ),
        migrations.AddIndex(
            model_name="searchlog",
            index=models.Index(
                fields=["created_at"], name="search_sear_created_558a5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchlog",
            index=models.Index(
                fields=["search_type"], name="search_sear_search__66c85a_idx"
            ),
        ),
    ]
