# Generated by Django 4.2.9 on 2025-01-16 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0002_add_pg_trgm"),
        ("search", "0002_initial"),
    ]

    operations = []
