# Generated by Django 4.2.9 on 2025-02-05 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the chat room",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the chat room was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the chat room was last updated"
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        help_text="Users participating in this chat room",
                        related_name="chat_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_chatroom",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the message",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(help_text="The message content")),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Whether the message has been read"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="When the message was read", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the message was created"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="File attached to this message",
                        null=True,
                        upload_to="chat_attachments/",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of the attached file",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        help_text="The chat room this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="User who sent this message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_message",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["room", "-created_at"],
                        name="chat_messag_room_id_edc775_idx",
                    ),
                    models.Index(
                        fields=["sender", "-created_at"],
                        name="chat_messag_sender__62c9f9_idx",
                    ),
                    models.Index(
                        fields=["is_read"], name="chat_messag_is_read_872c73_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["-updated_at"], name="chat_chatro_updated_fe8347_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["created_at"], name="chat_chatro_created_914abe_idx"
            ),
        ),
    ]
