# Generated by Django 4.2.9 on 2025-01-17 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_emailverificationotp_alter_user_managers_and_more"),
    ]

    operations = []
