# Generated by Django 4.2.9 on 2025-01-17 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_handle_chat_relationships"),
        ("users", "XXXX_handle_chat_relationships"),
    ]

    operations = []
