# Generated by Django 4.2.9 on 2025-01-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="account_privacy",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                default="PUBLIC",
                max_length=10,
            ),
        ),
    ]
