# Generated by Django 4.2.9 on 2025-02-03 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_userprofile_account_privacy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("FOLLOW", "Follow"),
                            ("LIKE", "Like"),
                            ("COMMENT", "Comment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("related_object_id", models.UUIDField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="users_notif_created_4b8aa8_idx"
                    ),
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="users_notif_recipie_458498_idx",
                    ),
                    models.Index(
                        fields=["is_read", "-created_at"],
                        name="users_notif_is_read_a243f6_idx",
                    ),
                ],
            },
        ),
    ]
